# pyproject.toml

[tool.djlint]
profile = "django"
indent = 4
max_line_length = 120
close_void_tags = true
max_attribute_length = 100
include = ["D001"]

# Use a single string for exclusions to avoid the TypeError
exclude = "**/migrations/**,**/static/**,**/node_modules/**"

# Use single strings for blank line settings
blank_line_before_tag = "block, for, if, extends, include"
blank_line_after_tag = "block, for, if, load, extends, include"
